// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqS3OXw6zABzNbNJ7MzHqAqi4sNBsLnmU',
    appId: '1:736883729105:android:7071cc9c6121014b6b1bf0',
    messagingSenderId: '736883729105',
    projectId: 'eine-liebe',
    databaseURL: 'https://eine-liebe.firebaseio.com',
    storageBucket: 'eine-liebe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5zpE5ofMq6jH8_msPe70ltXcai3mZQY0',
    appId: '1:736883729105:ios:0002a304d010bced6b1bf0',
    messagingSenderId: '736883729105',
    projectId: 'eine-liebe',
    databaseURL: 'https://eine-liebe.firebaseio.com',
    storageBucket: 'eine-liebe.appspot.com',
    iosClientId: '736883729105-ot9eoi0q9ahbc7j8nogb35kdhs5tsevs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
