name: Build Project
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter build apk

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign

